### ISSUE TITLE
Rake tasks don't appear in rake -T

### ISSUE THREAD

**Issue by m3talsmith** [biola/turnout#26]
It would be nice to have the rake tasks listed when I do a ```rake -T```. I though the gem hadn't installed correctly when I didn't see that.

**Comment by adamcrown** [comment]
Yeah, that's unfortunate I know. The reason is that Turnout doesn't technically have any Rake tasks. It has [Rake rules](https://github.com/biola/turnout/blob/master/lib/tasks/maintenance.rake) and rules don't show up with `rake -T`.

The rules are used so that `named_maintenance_file_paths` can be supported so you can do things like `rake maintenance:server:start` to shut down every app on a server, or whatever other sort of categories of apps you want to set up.

So for now, unfortunately, it looks like there's no good way to get the tasks to show up in `rake -T` unless somebody knows a trick that I don't.

**Comment by m3talsmith** [comment]
Hmm, fair enough. It is worth mentioning probably though in the documents.

On Mon, Nov 2, 2015 at 1:28 AM, Adam Crownoble <notifications@github.com>
wrote:

> Yeah, that's unfortunate I know. The reason is that Turnout doesn't
> technically have any Rake tasks. It has Rake rules
> <https://github.com/biola/turnout/blob/master/lib/tasks/maintenance.rake>
> and rules don't show up with rake -T.
>
> The rules are used so that named_maintenance_file_paths can be supported
> so you can do things like rake maintenance:server:start to shut down
> every app on a server, or whatever other sort of categories of apps you
> want to set up.
>
> So for now, unfortunately, it looks like there's no good way to get the
> tasks to show up in rake -T unless somebody knows a trick that I don't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biola/turnout/issues/26#issuecomment-152950202>.
>



-- 
Michael Christenson II
Senior Ruby Developer
p. (231)884-3024
e. michael@rebelhold.com
e. m3talsmith@gmail.com
g. http://github.com/m3talsmith
