### ISSUE TITLE
Further customization/configuration of maintenance.html

### ISSUE THREAD

**Issue by derosm2** [biola/turnout#30]
Since Turnout can already replace {{ reason }} inside a custom maintenance.html, I think it would be convenient to provide other replacements to enable more robust customization. I.E. having a hash of replacements that can be configured in the yaml file instead of just reason.

Ideally I'd want to be able to render a haml file and provide variables, but this text replacement may be a more immediate solution.

**Comment by adamcrown** [comment]
There's a pull request for ERB support: https://github.com/biola/turnout/pull/28. Since it's using tilt you could probably use HAML as well but I still need to review and play around with it.

The extra custom variables sounds like a good idea. I'd be happy to accept a pull request for that functionality. Otherwise, I'll see if I can get to it when I have some downtime.

**Comment by derosm2** [comment]
Thanks! That looks very promising!

**Comment by adamcrown** [comment]
FYI, I just merged that pull request to allow `maintenance.html.erb` files. So you should be able to customize as much as you like now. With that in mind I'm going to close this issue.
